tools:
    bcftools: /bcftools
    bedtools: /bedtools
    bwa: /bwa
    samtools: /samtools
    picard: /picard.jar
    trimmomatic: /trimmomatic-0.39.jar
    gatk: /gatk-4.1.6.0/gatk 
    annotator: /snpEff/snpEff.jar
    nextflow: /clockwork-0.9.0/results/nextflow
    remove_contam: /clockwork-0.9.0/nextflow/remove_contam.nf
    ref_fasta: /clockwork-0.9.0/OUT/ref.fa
    ref_metadata: /clockwork-0.9.0/OUT/remove_contam_metadata.tsv         
scripts:
    parser: /home/dieterbest/Analysis/varpipe_amplicon/tools/parse_annotation.py
    creater:  /home/dieterbest/Analysis/varpipe_amplicon/tools/create_annotation.py
    included:  /home/dieterbest/Analysis/varpipe_amplicon/tools/intervals.bed
    stats_estimator:  /home/dieterbest/Analysis/varpipe_amplicon/tools/stats_estimator.py
    bedlist_amp:  /home/dieterbest/Analysis/varpipe_amplicon/tools/amp_bed.txt      
    target_cov_estimator:  /home/dieterbest/Analysis/varpipe_amplicon/tools/target_coverage_estimator.py
    mutationloci:  /home/dieterbest/Analysis/varpipe_amplicon/tools/mutation_loci.txt
    create_report:  /home/dieterbest/Analysis/varpipe_amplicon/tools/create_report.py
    print_report: /home/dieterbest/Analysis/varpipe_amplicon/tools/pdf_print.py
other:
    threads: '12'
