tools:
    bcftools: /bcftools
    bedtools: /bedtools
    bwa: /bwa
    samtools: /samtools
    picard: /picard.jar
    trimmomatic: /trimmomatic-0.39.jar
    gatk: /gatk-4.1.6.0/gatk 
    annotator: /snpEff/snpEff.jar
    nextflow: /clockwork-0.9.0/results/nextflow
    remove_contam: /clockwork-0.9.0/nextflow/remove_contam.nf
    ref_fasta: /clockwork-0.9.0/OUT/ref.fa
    ref_metadata: /clockwork-0.9.0/OUT/remove_contam_metadata.tsv         
scripts:
    parser: /parse_annotation.py
    creater: /create_annotation.py
    included: /intervals.bed
    stats_estimator: /stats_estimator.py
    bedlist_amp: /amp_bed.txt      
    target_cov_estimator: /target_coverage_estimator.py
    mutationloci: /mutation_loci.txt
    create_report: /create_report.py
    print_report: /pdf_print.py
other:
    threads: '12'
